baseurl = "https://www.ardianta.com"
title = "Ardianta"
theme = "pargo"

googleAnalytics = "UA-54154424-1"
disqusShortname = "ardianta"

[permalinks]
  post = "/blog/:slug/"
  page = "/:slug/"

[params]
    # Site Author
    author = "Dian"

    # Description/subtitle for homepage
    description = "Hello, saya Dian. Blog ini belum jadi. Sabar ya..."

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    wight = 1
  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "https://ardiantapargo.deviantart.com/"
    wight = 2
  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ardiantapargo"
    wight = 3
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ardianta"
    wight = 4
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "http://feeds.feedburner.com/ardianta"
    wight = 5